# Generated by Django 4.1.4 on 2022-12-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptography_', '0002_alter_cryptofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptofile',
            name='encoded',
            field=models.BooleanField(blank=True),
        ),
    ]
