# Generated by Django 4.1.7 on 2023-02-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weathermodel',
            unique_together={('forecast_day', 'location')},
        ),
    ]
